version: '3.4'

services:
  sample.api:
    image: ${DOCKER_REGISTRY-}sampleapi
    build:
      context: .
      dockerfile: Sample.API/Dockerfile
    depends_on:
      - sample-db

  sample-db:
    image: postgres:latest
    container_name: SampleDb
    environment:
      - POSTGRES_DB=SampleDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5434:5432